version: '3.8'

services:
  # 1) Clúster CockroachDB de pruebas
  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroach-node
    command: start-single-node --insecure
    ports:
      - "26257:26257"   # SQL
      - "8080:8080"     # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data
      - ./db-init:/db-init   # Montamos aquí el SQL
    healthcheck:
      test: ["CMD", "cockroach", "sql", "--insecure", "--database=defaultdb", "-e", "SELECT 1"]
      interval: 5s
      retries: 5

  # 2) Init que carga el esquema en cuanto Cockroach esté listo
  cockroach-init:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroach-init
    depends_on:
      cockroach:
        condition: service_healthy
    entrypoint: [ "sh", "-ec",
      "echo '==> Importando esquema…'; \
       cockroach sql \
         --insecure \
         --host=cockroach \
         --port=26257 \
         --database=tickets \
         --file=/db-init/init_cockroach.sql; \
       echo '==> Esquema cargado.'"
    ]
    volumes:
      - ./db-init:/db-init

  # 3) Tu aplicación PHP/Apache
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    depends_on:
      - cockroach-init
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html

volumes:
  cockroach-data:
