version: '3.8'

services:
  # Servidor PHP/Apache
  php_app:
    build: ./php-server
    container_name: php_app
    ports:
      - "81:80"
    volumes:
      - ./php-server/app:/var/www/html
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    networks:
      - db_network

  # Nodos MySQL (3 instancias)
  mysql1:
    image: mysql:8.0
    container_name: mysql_node1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d  # Ejecuta scripts al iniciar
    ports:
      - "3306:3306"
    networks:
      - db_network

  mysql2:
    image: mysql:8.0
    container_name: mysql_node2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - db_network

  mysql3:
    image: mysql:8.0
    container_name: mysql_node3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - db_network

  # Opcional: Adminer para gestión de BD
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    networks:
      - db_network

networks:
  db_network:
    driver: bridge